# Generated by Django 5.2.16 on 2026-08-02 23:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть не меньше одного.')], verbose_name='Количество')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('recipient_name', models.CharField(blank=True, max_length=150, verbose_name='Имя получателя')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Итоговая стоимость')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('in_progress', 'В работе'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='orders_order_quantity_gte_1'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='orders_order_unit_price_gte_0'), models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='orders_order_total_price_gte_0')],
            },
        ),
    ]
